import React, { useRef, useState, useEffect } from 'react';
import Navigation from './components/Navigation';
import TelemetryCharts from './components/TelemetryCharts';
import InsightsPanel from './components/InsightsPanel';
import PostSessionSummary from './components/PostSessionSummary';
import ComplianceDashboard from './components/ComplianceDashboard';
import LiveTranscript from './components/LiveTranscript';
import ConsentModal from './components/ConsentModal';
import { ShieldCheck } from 'lucide-react';

function App() {
  const [sessionActive, setSessionActive] = useState(false);
  const [sessionEnded, setSessionEnded] = useState(false);
  const [engineStatus, setEngineStatus] = useState('baselining'); // 'baselining' or 'monitoring'
  const [telemetryData, setTelemetryData] = useState([]);
  const [currentView, setCurrentView] = useState('dashboard');
  const [liveLines, setLiveLines] = useState([]);
  const [showConsentModal, setShowConsentModal] = useState(false);
  const [fallbackMode, setFallbackMode] = useState(false);
  const [uploadedFile, setUploadedFile] = useState(null);
  
  const videoRef = useRef(null);
  const canvasRef = useRef(null);
  const streamRef = useRef(null);
  const pollingRef = useRef(null);
  const mediaRecorderRef = useRef(null);

  // Dynamic session ID generated by the backend
  const sessionIdRef = useRef(null);

  const handleStartRecording = () => {
    if (sessionActive) stopSession();
    setUploadedFile(null);
    setShowConsentModal(true);
  };

  const handleUploadData = () => {
    if (sessionActive) stopSession();
    document.getElementById('data-upload-input').click();
  };

  const handleStopSession = () => {
    if (sessionActive) {
      stopSession();
    }
  };

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setUploadedFile(file);
      setShowConsentModal(true);
    }
    e.target.value = null;
  };

  const handleConsentComplete = async ({ isConsentGiven, consent_id }) => {
    setShowConsentModal(false);
    setFallbackMode(!isConsentGiven);
    
    try {
      const response = await fetch('http://localhost:8000/api/v1/compliance/session', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          officer_id: 1, // Mocked officer (seed creates ID=1)
          subject_id: 1, // Mocked subject (seed creates ID=1)
          consent_id: consent_id,
          fallback_mode_active: !isConsentGiven
        })
      });
      if (response.ok) {
        const result = await response.json();
        sessionIdRef.current = result.session_id;
      } else {
        sessionIdRef.current = 1; // fallback
      }
    } catch (err) {
      console.error("Session creation error:", err);
      sessionIdRef.current = 1;
    }

    if (uploadedFile) {
      startSessionWithFile(uploadedFile);
    } else {
      startSessionWithWebcam();
    }
  };

  const startSessionWithWebcam = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true });
      videoRef.current.srcObject = stream;
      streamRef.current = stream;
      
      setSessionActive(true);
      setSessionEnded(false);
      setTelemetryData([]);
      setLiveLines([]);
      
      pollingRef.current = setInterval(captureAndSendFrame, 500);

      try {
        const startRecordingChunk = () => {
          if (!streamRef.current || !streamRef.current.active) return;
          
          const mediaRecorder = new MediaRecorder(streamRef.current, { mimeType: 'audio/webm' });
          mediaRecorderRef.current = mediaRecorder;
          
          mediaRecorder.ondataavailable = async (e) => {
            if (e.data.size > 0) {
              sendAudioChunk(e.data);
            }
          };
          
          mediaRecorder.start();
          
          setTimeout(() => {
            if (mediaRecorder.state !== 'inactive') {
              mediaRecorder.stop();
              if (streamRef.current && streamRef.current.active) {
                 startRecordingChunk();
              }
            }
          }, 5000);
        };
        
        startRecordingChunk();
      } catch (err) {
        console.error("Audio recording not supported or failed:", err);
      }

    } catch (err) {
      console.error("Error accessing webcam: ", err);
      alert("Could not access webcam. Please allow camera permissions.");
    }
  };

  const startSessionWithFile = async (file) => {
    try {
      const fileUrl = URL.createObjectURL(file);
      videoRef.current.src = fileUrl;
      videoRef.current.srcObject = null;
      
      // Strict Anti-Scrubbing Mechanism for Telemetry Integrity
      let lastTime = 0;
      videoRef.current.ontimeupdate = () => {
        if (videoRef.current && !videoRef.current.seeking) {
          lastTime = videoRef.current.currentTime;
        }
      };
      
      videoRef.current.onseeking = () => {
        if (videoRef.current && Math.abs(videoRef.current.currentTime - lastTime) > 0.5) {
          videoRef.current.currentTime = lastTime;
          // Could also show a toast notification here if we had one
        }
      };
      
      videoRef.current.onplay = () => {
        // Prevent multiple triggers when unpausing by removing the listener
        videoRef.current.onplay = null;
        
        const stream = videoRef.current.captureStream ? videoRef.current.captureStream() : videoRef.current.mozCaptureStream();
        if (!stream) {
          console.error("captureStream not supported");
          return;
        }
        
        streamRef.current = stream;
        
        setSessionActive(true);
        setSessionEnded(false);
        setTelemetryData([]);
        setLiveLines([]);
        
        // 2. Start polling the backend every 500ms (2 FPS for prototype)
        pollingRef.current = setInterval(captureAndSendFrame, 500);

        // 3. Start Audio Recording (5-second chunks with valid headers)
        try {
          const startRecordingChunk = () => {
            // Check if stream is still alive before creating a new recorder
            if (!streamRef.current || !streamRef.current.active) return;
            
            // Check if there's an audio track
            const audioTracks = streamRef.current.getAudioTracks();
            if (audioTracks.length === 0) {
              console.warn("No audio tracks found in the uploaded file stream.");
            }
            
            const options = MediaRecorder.isTypeSupported('audio/webm') ? { mimeType: 'audio/webm' } : {};
            const mediaRecorder = new MediaRecorder(streamRef.current, options);
            mediaRecorderRef.current = mediaRecorder;
            
            mediaRecorder.ondataavailable = async (e) => {
              if (e.data.size > 0) {
                sendAudioChunk(e.data);
              }
            };
            
            mediaRecorder.start();
            
            // Stop after 5 seconds to trigger ondataavailable and generate a full file with headers
            setTimeout(() => {
              if (mediaRecorder.state !== 'inactive') {
                mediaRecorder.stop();
                // Recursively start the next chunk if the session is still active
                if (streamRef.current && streamRef.current.active) {
                   startRecordingChunk();
                }
              }
            }, 5000);
          };
          
          startRecordingChunk();
        } catch (err) {
          console.error("Audio recording not supported or failed:", err);
        }
      };
      
      videoRef.current.onended = () => {
        stopSession();
      };
      
      videoRef.current.play();

    } catch (err) {
      console.error("Error setting up video file: ", err);
      alert("Could not process the uploaded file.");
    }
  };

  const stopSession = async () => {
    setSessionActive(false);
    setSessionEnded(true);
    if (pollingRef.current) clearInterval(pollingRef.current);
    if (mediaRecorderRef.current && mediaRecorderRef.current.state !== 'inactive') {
      mediaRecorderRef.current.stop();
    }
    if (streamRef.current) {
      streamRef.current.getTracks().forEach(track => track.stop());
    }
    if (videoRef.current) {
      videoRef.current.pause();
    }
    setUploadedFile(null);

    // Hit backend to clean up memory and finalize DB
    try {
      await fetch('http://localhost:8000/api/v1/compliance/end_session', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          session_id: sessionIdRef.current || 1, 
          officer_id: 1 // Mocked officer
        })
      });
    } catch (err) {
      console.error("Failed to end session cleanly on backend:", err);
    }
  };

  const handleDistress = async () => {
    try {
      await fetch('http://localhost:8000/api/v1/compliance/vulnerability', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ session_id: sessionIdRef.current || 1, officer_id: 1234, is_vulnerable: true, reason: "Officer triggered distress halt" })
      });
      setEngineStatus('HALTED (Distress)');
      if (pollingRef.current) clearInterval(pollingRef.current);
    } catch (err) {
      console.error(err);
    }
  };

  const resetToHome = () => {
    setSessionEnded(false);
    setEngineStatus('baselining');
    setTelemetryData([]);
    setLiveLines([]);
  };

  // Capture frame and send to FastAPI
  const captureAndSendFrame = async () => {
    if (!videoRef.current || !canvasRef.current) return;
    
    const video = videoRef.current;
    if (video.paused || video.ended) return;

    const canvas = canvasRef.current;
    
    // Draw current video frame to hidden canvas
    canvas.width = video.videoWidth;
    canvas.height = video.videoHeight;
    const ctx = canvas.getContext('2d');
    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
    
    // Convert canvas to Blob (JPEG)
    canvas.toBlob(async (blob) => {
      if (!blob) return;

      const formData = new FormData();
      formData.append('file', blob, 'frame.jpg');

      try {
        const response = await fetch(`http://localhost:8000/api/v1/inference/process_video?session_id=${sessionIdRef.current || 1}`, {
          method: 'POST',
          body: formData,
        });

        if (response.ok) {
          const result = await response.json();
          processBackendResult(result);
        } else {
          console.error("Backend error:", await response.text());
        }
      } catch (err) {
        console.error("Fetch error:", err);
      }
    }, 'image/jpeg', 0.8);
  };

  const sendAudioChunk = async (audioBlob) => {
    const formData = new FormData();
    formData.append('file', audioBlob, 'chunk.webm');
    
    try {
      const response = await fetch('http://localhost:8000/api/v1/inference/transcribe_chunk', {
        method: 'POST',
        body: formData,
      });
      if (response.ok) {
        const result = await response.json();
        
        // Discard delayed transcriptions if the video is currently paused
        if (videoRef.current && videoRef.current.paused) return;

        if (result.text && result.text.trim() !== '') {
          setLiveLines(prev => [...prev, {
            time: new Date().toLocaleTimeString([], { hour12: false, second: '2-digit', minute: '2-digit' }),
            text: result.text,
            language: result.language
          }]);
        }
      }
    } catch (err) {
      console.error("Transcription error:", err);
    }
  };

  const processBackendResult = (result) => {
    // Discard delayed telemetry if the video is currently paused
    if (videoRef.current && videoRef.current.paused) return;

    if (!result.cues) return;

    // The backend returns probabilities. If they are null, we are still baselining.
    // However, to make the prototype visually interesting immediately, if the backend 
    // is in baselining mode, we can inject some fake probabilities for the chart AFTER 5 seconds, 
    // or just strictly follow the status. Let's strictly follow the backend rules, 
    // but the backend was modified to return mock data if mediapipe failed. 

    // Update status
    const newStatus = result.cues.gaze_horizontal_ratio?.status || 'monitoring';
    setEngineStatus(newStatus);

    // Format data for Recharts
    const newPoint = {
      time: new Date().toLocaleTimeString([], { hour12: false, second: '2-digit', minute: '2-digit' }),
      // If probability is null (baselining), we plot exactly 0.5 (the baseline)
      gazeProbability: result.cues.gaze_horizontal_ratio?.probability ?? 0.5,
      pitchProbability: result.cues.head_pitch?.probability ?? 0.5,
      postureProbability: result.cues.shoulder_asymmetry?.probability ?? 0.5,
    };

    setTelemetryData(prev => {
      const updated = [...prev, newPoint];
      // Keep only last 20 points for visual clarity
      if (updated.length > 20) return updated.slice(updated.length - 20);
      return updated;
    });
  };

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (pollingRef.current) clearInterval(pollingRef.current);
      if (mediaRecorderRef.current && mediaRecorderRef.current.state !== 'inactive') {
        mediaRecorderRef.current.stop();
      }
      if (streamRef.current) streamRef.current.getTracks().forEach(track => track.stop());
    };
  }, []);

  return (
    <div className="app-container">
      <input 
        type="file" 
        id="data-upload-input" 
        accept="video/*,audio/*" 
        style={{ display: 'none' }} 
        onChange={handleFileChange} 
      />
      {showConsentModal && <ConsentModal onComplete={handleConsentComplete} />}
      
      <Navigation 
        sessionActive={sessionActive} 
        onStopSession={handleStopSession} 
        onStartRecording={handleStartRecording}
        onUploadData={handleUploadData}
        onDistress={handleDistress}
        currentView={currentView}
        setCurrentView={setCurrentView}
      />
      
      <main className="main-content">
        {currentView === 'compliance' ? (
          <ComplianceDashboard />
        ) : (
          <>
            <section style={styles.hero}>
          <h1 style={styles.heroTitle}>
            CONDUCT ETHICAL<br />
            INTERVIEWS WITH<br />
            PROBABILISTIC AI.
          </h1>
          <div style={styles.heroSubtitleContainer}>
            <div style={styles.heroSubtitle}>
              <div style={styles.smileIcon}>=)</div>
              <p style={styles.subtitleText}>
                SANKET guarantees compliance with Indian evidentiary law by 
                forbidding deterministic "lie detection" outputs.
              </p>
            </div>
          </div>
        </section>

        {sessionEnded ? (
          <PostSessionSummary telemetryData={telemetryData} onReset={resetToHome} />
        ) : (
          <>
            <section className="responsive-grid">
              {/* Left Column: Video Feed & Transcript */}
              <div style={styles.leftColumn}>
                <div className="card" style={styles.videoCard}>
                  <div style={styles.videoHeader}>
              <span style={{ fontWeight: '600', fontSize: '1.1rem', letterSpacing: '-0.01em' }}>Live Feed (Subject A)</span>
              {sessionActive && <span style={styles.recordingDot}></span>}
            </div>
            
            <div style={styles.videoWrapper}>
              {!sessionActive && (
                <div style={styles.videoPlaceholder}>
                  <p style={{ fontSize: '1.1rem', fontWeight: '500', color: 'var(--text-secondary)' }}>Click "Start Recording" or "Upload Data" to begin telemetry.</p>
                </div>
              )}
              <video 
                ref={videoRef} 
                autoPlay 
                playsInline 
                controls={sessionActive && !!uploadedFile}
                muted={!uploadedFile}
                style={{ 
                  ...styles.video, 
                  display: sessionActive ? 'block' : 'none',
                  transform: uploadedFile ? 'none' : 'scaleX(-1)',
                  objectFit: uploadedFile ? 'contain' : 'cover'
                }} 
              />
              {/* Hidden canvas for extracting frames */}
                    <canvas ref={canvasRef} style={{ display: 'none' }} />
                  </div>
                </div>
                <LiveTranscript sessionActive={sessionActive} liveLines={liveLines} />
              </div>

              {/* Right Column: Telemetry */}
              {fallbackMode ? (
                <div style={{...styles.telemetryWrapper, display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: 'var(--bg-secondary)', borderRadius: '8px', border: '1px solid var(--border-light)'}}>
                  <div style={{textAlign: 'center', padding: '2rem'}}>
                    <ShieldCheck size={48} color="var(--status-active)" style={{marginBottom: '1rem'}} />
                    <h3 style={{color: 'var(--text-primary)', marginBottom: '0.5rem'}}>Fallback Mode Active</h3>
                    <p style={{color: 'var(--text-secondary)'}}>Consent was denied. AI behavioral telemetry is strictly disabled in compliance with the DPDP Act 2023.</p>
                  </div>
                </div>
              ) : (
                <div style={styles.telemetryWrapper}>
                  <TelemetryCharts data={telemetryData} status={engineStatus} />
                </div>
              )}
            </section>

        {/* Real-time Interpretation Panel */}
        {!fallbackMode && (
          <section>
            <InsightsPanel 
              latestData={telemetryData.length > 0 ? telemetryData[telemetryData.length - 1] : null} 
              isBaselining={engineStatus === 'baselining'} 
            />
          </section>
        )}
        </>
        )}
      </>
      )}
      </main>
    </div>
  );
}

const styles = {
  hero: {
    marginBottom: '4rem',
    position: 'relative',
  },
  heroTitle: {
    fontSize: '5.5rem',
    fontWeight: '700',
    letterSpacing: '-0.04em',
    lineHeight: '1.0',
    color: 'var(--text-primary)',
    marginBottom: '4rem',
  },
  heroSubtitleContainer: {
    borderTop: '1px solid var(--border-light)',
    paddingTop: '2rem',
    width: '100%',
  },
  heroSubtitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
    maxWidth: '600px',
  },
  smileIcon: {
    fontSize: '1.2rem',
    fontWeight: '600',
    color: 'var(--text-primary)',
    transform: 'rotate(90deg)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '2px solid var(--text-primary)',
    borderRadius: '50%',
    width: '40px',
    height: '40px',
    flexShrink: 0,
    paddingBottom: '2px'
  },
  subtitleText: {
    margin: 0,
    fontSize: '1.1rem',
    lineHeight: '1.6',
    color: 'var(--text-secondary)',
    fontWeight: '400',
  },
  leftColumn: {
    display: 'flex',
    flexDirection: 'column',
  },
  videoCard: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
  videoHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1rem',
  },
  recordingDot: {
    width: '10px',
    height: '10px',
    backgroundColor: '#FF3B30',
    borderRadius: '50%',
    animation: 'pulse 1.5s infinite',
  },
  videoWrapper: {
    flex: 1,
    backgroundColor: 'var(--bg-secondary)',
    borderRadius: '8px',
    overflow: 'hidden',
    position: 'relative',
    border: '1px solid var(--border-light)',
  },
  videoPlaceholder: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'var(--text-secondary)',
    padding: '2rem',
    textAlign: 'center',
  },
  video: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000'
  },
  telemetryWrapper: {
    height: '100%',
  }
};

export default App;
